version: "3.9"

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=customers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/db-files
    volumes:
      - postgres:/var/lib/postgresql/data/db-files
    networks:
      - postgres
    restart: always

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    volumes:
      - adminer:/var/lib/adminer
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  adminer:
